# Site settings
title:          Paycis
description:    "Minimal Jekyll theme for storytellers"
#baseurl:        "/tale"
url:            "https://willing1026.github.io"

# google analytics
google_analytics_id: UA-113210161-1

# Author
author:
  name:         Paycis
  #url:          https://chester.how
  email:        willing1026@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
